version: "3.9"
   
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_DEBUG=True
      - APP_SECRET_KEY=PdxZDkWzUW4SSAOt3tjlqQ6u4K+IY4vmalX
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine3.16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres